{% set version = "1.0-2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-densestbayes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/densEstBayes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/densEstBayes/densEstBayes_{{ version }}.tar.gz
  sha256: 8361df9cd4b34fabfca19360bb680a8a3c68386a72bb69cf00dfa19daf97b679

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppparallel
    - r-stanheaders
    - r-rstantools
    - r-nlme
    - r-rstan
    - libblas  # [not win]
  run:
    - r-base
    #- r-bh
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppparallel
    - r-stanheaders
    - r-rstantools
    - r-nlme
    - r-rstan

test:
  commands:
    - $R -e "library('densEstBayes')"           # [not win]
    - "\"%R%\" -e \"library('densEstBayes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=densEstBayes
  license: GPL-2.0-or-later
  summary: 'Bayesian density estimates for univariate continuous random samples are provided using the Bayesian inference engine paradigm. The engine options are: Hamiltonian Monte Carlo, the no U-turn sampler, semiparametric mean field variational Bayes and slice sampling. The methodology is described in Wand and Yu (2020)
    <arXiv:2009.06182>.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
